import { describe, expect, test } from 'untestutils/vitest';

/**
 * Naive baseline file 7/10 — own recipe id (app07), own prepare.
 * Generated by scripts/generate-e2e.mjs — do not hand-edit; re-run generator.
 */
describe('mass-nuxt naive file-07', () => {
  test.override({ harness: 'app07' });

  test('item-detail-75', async ({ page, goto }) => {
    await goto('/items/75', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-75-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-75-copy"]')).toContainText('75');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-76-ok"]')).toBeVisible();
  });

  test('item-detail-76', async ({ page, goto }) => {
    await goto('/items/76', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-76-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-76-copy"]')).toContainText('76');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-77-ok"]')).toBeVisible();
  });

  test('item-detail-77', async ({ page, goto }) => {
    await goto('/items/77', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-77-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-77-copy"]')).toContainText('77');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-78-ok"]')).toBeVisible();
  });

  test('item-detail-78', async ({ page, goto }) => {
    await goto('/items/78', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-78-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-78-copy"]')).toContainText('78');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-79-ok"]')).toBeVisible();
  });

  test('item-detail-79', async ({ page, goto }) => {
    await goto('/items/79', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-79-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-79-copy"]')).toContainText('79');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-80-ok"]')).toBeVisible();
  });

  test('item-detail-80', async ({ page, goto }) => {
    await goto('/items/80', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-80-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-80-copy"]')).toContainText('80');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-81-ok"]')).toBeVisible();
  });

  test('session-cookie-en', async ({ page, goto }) => {
    await goto('/session', { waitUntil: 'hydration' });
    await page.locator('[data-action="set-de"]').click();
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=de');
    await page.locator('[data-nav="home"]').click();
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible();
    await page.locator('[data-nav="session"]').click();
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=de');
    await page.locator('[data-action="set-en"]').click();
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=en');
  });

  test('search-en', async ({ page, goto }) => {
    await goto('/search', { waitUntil: 'hydration' });
    await page.locator('[data-mark="search-input"]').fill('locale-en');
    await page.locator('[data-action="search"]').click();
    await expect(page.locator('[data-mark="search-result"]')).toHaveText('query=locale-en');
  });

  test('session-cookie-de', async ({ page, goto }) => {
    await goto('/session', { waitUntil: 'hydration' });
    await page.locator('[data-action="set-de"]').click();
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=de');
    await page.locator('[data-nav="home"]').click();
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible();
    await page.locator('[data-nav="session"]').click();
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=de');
    await page.locator('[data-action="set-en"]').click();
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=en');
  });

  test('search-de', async ({ page, goto }) => {
    await goto('/search', { waitUntil: 'hydration' });
    await page.locator('[data-mark="search-input"]').fill('locale-de');
    await page.locator('[data-action="search"]').click();
    await expect(page.locator('[data-mark="search-result"]')).toHaveText('query=locale-de');
  });

  test('session-cookie-fr', async ({ page, goto }) => {
    await goto('/session', { waitUntil: 'hydration' });
    await page.locator('[data-action="set-de"]').click();
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=de');
    await page.locator('[data-nav="home"]').click();
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible();
    await page.locator('[data-nav="session"]').click();
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=de');
    await page.locator('[data-action="set-en"]').click();
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=en');
  });

  test('search-fr', async ({ page, goto }) => {
    await goto('/search', { waitUntil: 'hydration' });
    await page.locator('[data-mark="search-input"]').fill('locale-fr');
    await page.locator('[data-action="search"]').click();
    await expect(page.locator('[data-mark="search-result"]')).toHaveText('query=locale-fr');
  });

  test('session-cookie-es', async ({ page, goto }) => {
    await goto('/session', { waitUntil: 'hydration' });
    await page.locator('[data-action="set-de"]').click();
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=de');
    await page.locator('[data-nav="home"]').click();
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible();
    await page.locator('[data-nav="session"]').click();
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=de');
    await page.locator('[data-action="set-en"]').click();
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=en');
  });

  test('search-es', async ({ page, goto }) => {
    await goto('/search', { waitUntil: 'hydration' });
    await page.locator('[data-mark="search-input"]').fill('locale-es');
    await page.locator('[data-action="search"]').click();
    await expect(page.locator('[data-mark="search-result"]')).toHaveText('query=locale-es');
  });

  test('session-cookie-it', async ({ page, goto }) => {
    await goto('/session', { waitUntil: 'hydration' });
    await page.locator('[data-action="set-de"]').click();
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=de');
    await page.locator('[data-nav="home"]').click();
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible();
    await page.locator('[data-nav="session"]').click();
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=de');
    await page.locator('[data-action="set-en"]').click();
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=en');
  });
});
