import { describe, expect, test } from 'untestutils/vitest';

/**
 * Naive baseline file 2/10 — own recipe id (app02), own prepare.
 * Generated by scripts/generate-e2e.mjs — do not hand-edit; re-run generator.
 */
describe('mass-nuxt naive file-02', () => {
  test.override({ harness: 'app02' });

  test('locale-flow-ko', async ({ page, goto }) => {
    await goto('/locale/ko', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="locale-ko-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="locale-ko-copy"]')).toContainText('ko');
    await page.locator('[data-nav="back-home"]').click();
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible();
    await page.locator('[data-nav="locale-ko"]').click();
    await expect(page.locator('[data-mark="locale-ko-ok"]')).toBeVisible();
  });

  test('item-detail-1', async ({ page, goto }) => {
    await goto('/items/1', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-1-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-1-copy"]')).toContainText('1');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-2-ok"]')).toBeVisible();
  });

  test('item-detail-2', async ({ page, goto }) => {
    await goto('/items/2', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-2-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-2-copy"]')).toContainText('2');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-3-ok"]')).toBeVisible();
  });

  test('item-detail-3', async ({ page, goto }) => {
    await goto('/items/3', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-3-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-3-copy"]')).toContainText('3');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-4-ok"]')).toBeVisible();
  });

  test('item-detail-4', async ({ page, goto }) => {
    await goto('/items/4', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-4-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-4-copy"]')).toContainText('4');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-5-ok"]')).toBeVisible();
  });

  test('item-detail-5', async ({ page, goto }) => {
    await goto('/items/5', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-5-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-5-copy"]')).toContainText('5');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-6-ok"]')).toBeVisible();
  });

  test('item-detail-6', async ({ page, goto }) => {
    await goto('/items/6', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-6-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-6-copy"]')).toContainText('6');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-7-ok"]')).toBeVisible();
  });

  test('item-detail-7', async ({ page, goto }) => {
    await goto('/items/7', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-7-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-7-copy"]')).toContainText('7');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-8-ok"]')).toBeVisible();
  });

  test('item-detail-8', async ({ page, goto }) => {
    await goto('/items/8', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-8-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-8-copy"]')).toContainText('8');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-9-ok"]')).toBeVisible();
  });

  test('item-detail-9', async ({ page, goto }) => {
    await goto('/items/9', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-9-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-9-copy"]')).toContainText('9');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-10-ok"]')).toBeVisible();
  });

  test('item-detail-10', async ({ page, goto }) => {
    await goto('/items/10', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-10-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-10-copy"]')).toContainText('10');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-11-ok"]')).toBeVisible();
  });

  test('item-detail-11', async ({ page, goto }) => {
    await goto('/items/11', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-11-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-11-copy"]')).toContainText('11');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-12-ok"]')).toBeVisible();
  });

  test('item-detail-12', async ({ page, goto }) => {
    await goto('/items/12', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-12-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-12-copy"]')).toContainText('12');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-13-ok"]')).toBeVisible();
  });

  test('item-detail-13', async ({ page, goto }) => {
    await goto('/items/13', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-13-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-13-copy"]')).toContainText('13');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-14-ok"]')).toBeVisible();
  });

  test('item-detail-14', async ({ page, goto }) => {
    await goto('/items/14', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-14-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-14-copy"]')).toContainText('14');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-15-ok"]')).toBeVisible();
  });
});
