import { describe, expect, test } from 'untestutils/vitest'

/**
 * Naive baseline file 10/10 — own recipe id (app10), own prepare.
 * Generated by scripts/generate-e2e.mjs — do not hand-edit; re-run generator.
 */
describe('mass-nuxt naive file-10', () => {
  test.override({ harness: 'app10' })

  test('about-roundtrip-136', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('about-roundtrip-137', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('about-roundtrip-138', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('about-roundtrip-139', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('about-roundtrip-140', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('about-roundtrip-141', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('about-roundtrip-142', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('about-roundtrip-143', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('about-roundtrip-144', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('about-roundtrip-145', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('about-roundtrip-146', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('about-roundtrip-147', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('about-roundtrip-148', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('about-roundtrip-149', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('about-roundtrip-150', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })
})
