import { describe, expect, test } from 'untestutils/vitest'

/**
 * Naive baseline file 8/10 — own recipe id (app08), own prepare.
 * Generated by scripts/generate-e2e.mjs — do not hand-edit; re-run generator.
 */
describe('mass-nuxt naive file-08', () => {
  test.override({ harness: 'app08' })

  test('search-it', async ({ page, goto }) => {
    await goto('/search', { waitUntil: 'hydration' })
    await page.locator('[data-mark="search-input"]').fill("locale-it")
    await page.locator('[data-action="search"]').click()
    await expect(page.locator('[data-mark="search-result"]')).toHaveText("query=locale-it")
  })

  test('session-cookie-pt', async ({ page, goto }) => {
    await goto('/session', { waitUntil: 'hydration' })
    await page.locator('[data-action="set-de"]').click()
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=de')
    await page.locator('[data-nav="home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
    await page.locator('[data-nav="session"]').click()
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=de')
    await page.locator('[data-action="set-en"]').click()
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=en')
  })

  test('search-pt', async ({ page, goto }) => {
    await goto('/search', { waitUntil: 'hydration' })
    await page.locator('[data-mark="search-input"]').fill("locale-pt")
    await page.locator('[data-action="search"]').click()
    await expect(page.locator('[data-mark="search-result"]')).toHaveText("query=locale-pt")
  })

  test('session-cookie-nl', async ({ page, goto }) => {
    await goto('/session', { waitUntil: 'hydration' })
    await page.locator('[data-action="set-de"]').click()
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=de')
    await page.locator('[data-nav="home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
    await page.locator('[data-nav="session"]').click()
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=de')
    await page.locator('[data-action="set-en"]').click()
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=en')
  })

  test('search-nl', async ({ page, goto }) => {
    await goto('/search', { waitUntil: 'hydration' })
    await page.locator('[data-mark="search-input"]').fill("locale-nl")
    await page.locator('[data-action="search"]').click()
    await expect(page.locator('[data-mark="search-result"]')).toHaveText("query=locale-nl")
  })

  test('session-cookie-pl', async ({ page, goto }) => {
    await goto('/session', { waitUntil: 'hydration' })
    await page.locator('[data-action="set-de"]').click()
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=de')
    await page.locator('[data-nav="home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
    await page.locator('[data-nav="session"]').click()
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=de')
    await page.locator('[data-action="set-en"]').click()
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=en')
  })

  test('search-pl', async ({ page, goto }) => {
    await goto('/search', { waitUntil: 'hydration' })
    await page.locator('[data-mark="search-input"]').fill("locale-pl")
    await page.locator('[data-action="search"]').click()
    await expect(page.locator('[data-mark="search-result"]')).toHaveText("query=locale-pl")
  })

  test('session-cookie-ja', async ({ page, goto }) => {
    await goto('/session', { waitUntil: 'hydration' })
    await page.locator('[data-action="set-de"]').click()
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=de')
    await page.locator('[data-nav="home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
    await page.locator('[data-nav="session"]').click()
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=de')
    await page.locator('[data-action="set-en"]').click()
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=en')
  })

  test('search-ja', async ({ page, goto }) => {
    await goto('/search', { waitUntil: 'hydration' })
    await page.locator('[data-mark="search-input"]').fill("locale-ja")
    await page.locator('[data-action="search"]').click()
    await expect(page.locator('[data-mark="search-result"]')).toHaveText("query=locale-ja")
  })

  test('session-cookie-ko', async ({ page, goto }) => {
    await goto('/session', { waitUntil: 'hydration' })
    await page.locator('[data-action="set-de"]').click()
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=de')
    await page.locator('[data-nav="home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
    await page.locator('[data-nav="session"]').click()
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=de')
    await page.locator('[data-action="set-en"]').click()
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=en')
  })

  test('search-ko', async ({ page, goto }) => {
    await goto('/search', { waitUntil: 'hydration' })
    await page.locator('[data-mark="search-input"]').fill("locale-ko")
    await page.locator('[data-action="search"]').click()
    await expect(page.locator('[data-mark="search-result"]')).toHaveText("query=locale-ko")
  })

  test('about-roundtrip-117', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('about-roundtrip-118', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('about-roundtrip-119', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('about-roundtrip-120', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })
})
