/**
 * Generates browser multi-step e2e for shared + naive modes.
 * 10 files × 15 scenarios = 150 tests (Playwright goto + hydration + clicks).
 *
 * Run: node scripts/generate-e2e.mjs
 */
import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const FILES = 10;
const PER_FILE = 15;

const locales = ['en', 'de', 'fr', 'es', 'it', 'pt', 'nl', 'pl', 'ja', 'ko'];

/** @typedef {{ kind: string, name: string, args?: Record<string, string> }} Scenario */

/** @returns {Scenario[]} */
function allScenarios() {
  /** @type {Scenario[]} */
  const out = [];

  out.push({ kind: 'home-hydrate', name: 'home-hydrate' });
  out.push({ kind: 'about-roundtrip', name: 'about-roundtrip' });
  out.push({ kind: 'client-bump', name: 'client-bump' });
  out.push({ kind: 'search-submit', name: 'search-submit', args: { q: 'nuxt-mass' } });
  out.push({ kind: 'session-cookie', name: 'session-cookie-de' });
  out.push({ kind: 'api-health', name: 'api-health' });

  for (const code of locales) {
    out.push({ kind: 'locale-flow', name: `locale-flow-${code}`, args: { code } });
  }

  for (let id = 1; id <= 40; id++) {
    out.push({
      kind: 'item-detail',
      name: `item-detail-${id}`,
      args: { id: String(id) },
    });
  }

  // more unique multi-step flows instead of toy pads
  for (let id = 41; id <= 80; id++) {
    out.push({
      kind: 'item-detail',
      name: `item-detail-${id}`,
      args: { id: String(id) },
    });
  }
  for (const code of locales) {
    out.push({ kind: 'session-cookie', name: `session-cookie-${code}` });
    out.push({
      kind: 'search-submit',
      name: `search-${code}`,
      args: { q: `locale-${code}` },
    });
  }
  while (out.length < FILES * PER_FILE) {
    const n = out.length + 1;
    out.push({
      kind: 'about-roundtrip',
      name: `about-roundtrip-${n}`,
    });
  }
  return out.slice(0, FILES * PER_FILE);
}

function renderSharedFile(fileIndex, chunk) {
  const pad = String(fileIndex + 1).padStart(2, '0');
  return `import { describe, expect, test } from 'untestutils/vitest'

/**
 * Mass live browser suite file ${fileIndex + 1}/${FILES} — shared Nuxt prepare.
 * Generated by scripts/generate-e2e.mjs — do not hand-edit; re-run generator.
 */
describe('mass-nuxt shared file-${pad}', () => {
  test.override({ harness: 'app' })

${chunk.map((s) => renderTest(s)).join('\n\n')}
})
`;
}

function renderNaiveFile(fileIndex, chunk) {
  const pad = String(fileIndex + 1).padStart(2, '0');
  const harness = `app${pad}`;
  return `import { describe, expect, test } from 'untestutils/vitest'

/**
 * Naive baseline file ${fileIndex + 1}/${FILES} — own recipe id (${harness}), own prepare.
 * Generated by scripts/generate-e2e.mjs — do not hand-edit; re-run generator.
 */
describe('mass-nuxt naive file-${pad}', () => {
  test.override({ harness: '${harness}' })

${chunk.map((s) => renderTest(s)).join('\n\n')}
})
`;
}

/** @param {Scenario} s */
function renderTest(s) {
  const args = s.args ?? {};
  switch (s.kind) {
    case 'home-hydrate':
      return `  test('${s.name}', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
    await expect(page.locator('[data-mark="home-copy"]')).toContainText('mass-nuxt')
    await expect(page.locator('[data-mark="nav"]')).toBeVisible()
  })`;
    case 'about-roundtrip':
      return `  test('${s.name}', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })`;
    case 'client-bump':
      return `  test('${s.name}', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await expect(page.locator('[data-mark="home-count"]')).toHaveText('count=0')
    await page.locator('[data-action="bump"]').click()
    await page.locator('[data-action="bump"]').click()
    await expect(page.locator('[data-mark="home-count"]')).toHaveText('count=2')
  })`;
    case 'search-submit':
      return `  test('${s.name}', async ({ page, goto }) => {
    await goto('/search', { waitUntil: 'hydration' })
    await page.locator('[data-mark="search-input"]').fill(${JSON.stringify(args.q)})
    await page.locator('[data-action="search"]').click()
    await expect(page.locator('[data-mark="search-result"]')).toHaveText(${JSON.stringify(`query=${args.q}`)})
  })`;
    case 'session-cookie':
      return `  test('${s.name}', async ({ page, goto }) => {
    await goto('/session', { waitUntil: 'hydration' })
    await page.locator('[data-action="set-de"]').click()
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=de')
    await page.locator('[data-nav="home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
    await page.locator('[data-nav="session"]').click()
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=de')
    await page.locator('[data-action="set-en"]').click()
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=en')
  })`;
    case 'api-health':
      return `  test('${s.name}', async ({ request, goto, page }) => {
    const res = await request.get('/api/health')
    expect(res.ok()).toBe(true)
    expect(await res.json()).toMatchObject({ ok: true })
    await goto('/', { waitUntil: 'hydration' })
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })`;
    case 'locale-flow':
      return `  test('${s.name}', async ({ page, goto }) => {
    await goto(${JSON.stringify(`/locale/${args.code}`)}, { waitUntil: 'hydration' })
    await expect(page.locator(${JSON.stringify(`[data-mark="locale-${args.code}-ok"]`)})).toBeVisible()
    await expect(page.locator(${JSON.stringify(`[data-mark="locale-${args.code}-copy"]`)})).toContainText(${JSON.stringify(args.code)})
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
    await page.locator(${JSON.stringify(`[data-nav="locale-${args.code}"]`)}).click()
    await expect(page.locator(${JSON.stringify(`[data-mark="locale-${args.code}-ok"]`)})).toBeVisible()
  })`;
    case 'item-detail':
      return `  test('${s.name}', async ({ page, goto }) => {
    await goto(${JSON.stringify(`/items/${args.id}`)}, { waitUntil: 'hydration' })
    await expect(page.locator(${JSON.stringify(`[data-mark="item-${args.id}-ok"]`)})).toBeVisible()
    await expect(page.locator(${JSON.stringify(`[data-mark="item-${args.id}-copy"]`)})).toContainText(${JSON.stringify(args.id)})
    await page.locator('[data-nav="next-item"]').click()
    await expect(page.locator(${JSON.stringify(`[data-mark="item-${Number(args.id) + 1}-ok"]`)})).toBeVisible()
  })`;
    default:
      throw new Error(`unknown kind ${s.kind}`);
  }
}

const scenarios = allScenarios();
const sharedDir = join(root, '../e2e');
const naiveDir = join(root, '../e2e-naive');
rmSync(sharedDir, { recursive: true, force: true });
rmSync(naiveDir, { recursive: true, force: true });
mkdirSync(sharedDir, { recursive: true });
mkdirSync(naiveDir, { recursive: true });

for (let f = 0; f < FILES; f++) {
  const chunk = scenarios.slice(f * PER_FILE, (f + 1) * PER_FILE);
  const pad = String(f + 1).padStart(2, '0');
  writeFileSync(join(sharedDir, `file-${pad}.spec.ts`), renderSharedFile(f, chunk));
  writeFileSync(join(naiveDir, `file-${pad}.spec.ts`), renderNaiveFile(f, chunk));
}

console.log(
  `wrote ${FILES}×${PER_FILE}=${FILES * PER_FILE} shared → ${sharedDir}\n` +
    `wrote ${FILES}×${PER_FILE}=${FILES * PER_FILE} naive  → ${naiveDir}`,
);
