import { describe, expect, test } from 'untestutils/vitest'

/**
 * Mass live browser suite file 9/10 — shared Nuxt prepare.
 * Generated by scripts/generate-e2e.mjs — do not hand-edit; re-run generator.
 */
describe('mass-nuxt shared file-09', () => {
  test.override({ harness: 'app' })

  test('about-roundtrip-121', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('about-roundtrip-122', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('about-roundtrip-123', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('about-roundtrip-124', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('about-roundtrip-125', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('about-roundtrip-126', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('about-roundtrip-127', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('about-roundtrip-128', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('about-roundtrip-129', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('about-roundtrip-130', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('about-roundtrip-131', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('about-roundtrip-132', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('about-roundtrip-133', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('about-roundtrip-134', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('about-roundtrip-135', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })
})
