import { describe, expect, test } from 'untestutils/vitest';

/**
 * Mass live browser suite file 4/10 — shared Nuxt prepare.
 * Generated by scripts/generate-e2e.mjs — do not hand-edit; re-run generator.
 */
describe('mass-nuxt shared file-04', () => {
  test.override({ harness: 'app' });

  test('item-detail-30', async ({ page, goto }) => {
    await goto('/items/30', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-30-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-30-copy"]')).toContainText('30');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-31-ok"]')).toBeVisible();
  });

  test('item-detail-31', async ({ page, goto }) => {
    await goto('/items/31', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-31-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-31-copy"]')).toContainText('31');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-32-ok"]')).toBeVisible();
  });

  test('item-detail-32', async ({ page, goto }) => {
    await goto('/items/32', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-32-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-32-copy"]')).toContainText('32');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-33-ok"]')).toBeVisible();
  });

  test('item-detail-33', async ({ page, goto }) => {
    await goto('/items/33', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-33-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-33-copy"]')).toContainText('33');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-34-ok"]')).toBeVisible();
  });

  test('item-detail-34', async ({ page, goto }) => {
    await goto('/items/34', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-34-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-34-copy"]')).toContainText('34');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-35-ok"]')).toBeVisible();
  });

  test('item-detail-35', async ({ page, goto }) => {
    await goto('/items/35', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-35-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-35-copy"]')).toContainText('35');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-36-ok"]')).toBeVisible();
  });

  test('item-detail-36', async ({ page, goto }) => {
    await goto('/items/36', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-36-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-36-copy"]')).toContainText('36');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-37-ok"]')).toBeVisible();
  });

  test('item-detail-37', async ({ page, goto }) => {
    await goto('/items/37', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-37-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-37-copy"]')).toContainText('37');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-38-ok"]')).toBeVisible();
  });

  test('item-detail-38', async ({ page, goto }) => {
    await goto('/items/38', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-38-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-38-copy"]')).toContainText('38');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-39-ok"]')).toBeVisible();
  });

  test('item-detail-39', async ({ page, goto }) => {
    await goto('/items/39', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-39-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-39-copy"]')).toContainText('39');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-40-ok"]')).toBeVisible();
  });

  test('item-detail-40', async ({ page, goto }) => {
    await goto('/items/40', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-40-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-40-copy"]')).toContainText('40');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-41-ok"]')).toBeVisible();
  });

  test('item-detail-41', async ({ page, goto }) => {
    await goto('/items/41', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-41-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-41-copy"]')).toContainText('41');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-42-ok"]')).toBeVisible();
  });

  test('item-detail-42', async ({ page, goto }) => {
    await goto('/items/42', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-42-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-42-copy"]')).toContainText('42');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-43-ok"]')).toBeVisible();
  });

  test('item-detail-43', async ({ page, goto }) => {
    await goto('/items/43', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-43-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-43-copy"]')).toContainText('43');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-44-ok"]')).toBeVisible();
  });

  test('item-detail-44', async ({ page, goto }) => {
    await goto('/items/44', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-44-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-44-copy"]')).toContainText('44');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-45-ok"]')).toBeVisible();
  });
});
