import { describe, expect, test } from 'untestutils/vitest'

/**
 * Mass live browser suite file 1/10 — shared Nuxt prepare.
 * Generated by scripts/generate-e2e.mjs — do not hand-edit; re-run generator.
 */
describe('mass-nuxt shared file-01', () => {
  test.override({ harness: 'app' })

  test('home-hydrate', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
    await expect(page.locator('[data-mark="home-copy"]')).toContainText('mass-nuxt')
    await expect(page.locator('[data-mark="nav"]')).toBeVisible()
  })

  test('about-roundtrip', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await page.locator('[data-nav="about"]').click()
    await expect(page.locator('[data-mark="about-ok"]')).toBeVisible()
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('client-bump', async ({ page, goto }) => {
    await goto('/', { waitUntil: 'hydration' })
    await expect(page.locator('[data-mark="home-count"]')).toHaveText('count=0')
    await page.locator('[data-action="bump"]').click()
    await page.locator('[data-action="bump"]').click()
    await expect(page.locator('[data-mark="home-count"]')).toHaveText('count=2')
  })

  test('search-submit', async ({ page, goto }) => {
    await goto('/search', { waitUntil: 'hydration' })
    await page.locator('[data-mark="search-input"]').fill("nuxt-mass")
    await page.locator('[data-action="search"]').click()
    await expect(page.locator('[data-mark="search-result"]')).toHaveText("query=nuxt-mass")
  })

  test('session-cookie-de', async ({ page, goto }) => {
    await goto('/session', { waitUntil: 'hydration' })
    await page.locator('[data-action="set-de"]').click()
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=de')
    await page.locator('[data-nav="home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
    await page.locator('[data-nav="session"]').click()
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=de')
    await page.locator('[data-action="set-en"]').click()
    await expect(page.locator('[data-mark="session-locale"]')).toHaveText('locale=en')
  })

  test('api-health', async ({ request, goto, page }) => {
    const res = await request.get('/api/health')
    expect(res.ok()).toBe(true)
    expect(await res.json()).toMatchObject({ ok: true })
    await goto('/', { waitUntil: 'hydration' })
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
  })

  test('locale-flow-en', async ({ page, goto }) => {
    await goto("/locale/en", { waitUntil: 'hydration' })
    await expect(page.locator("[data-mark=\"locale-en-ok\"]")).toBeVisible()
    await expect(page.locator("[data-mark=\"locale-en-copy\"]")).toContainText("en")
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
    await page.locator("[data-nav=\"locale-en\"]").click()
    await expect(page.locator("[data-mark=\"locale-en-ok\"]")).toBeVisible()
  })

  test('locale-flow-de', async ({ page, goto }) => {
    await goto("/locale/de", { waitUntil: 'hydration' })
    await expect(page.locator("[data-mark=\"locale-de-ok\"]")).toBeVisible()
    await expect(page.locator("[data-mark=\"locale-de-copy\"]")).toContainText("de")
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
    await page.locator("[data-nav=\"locale-de\"]").click()
    await expect(page.locator("[data-mark=\"locale-de-ok\"]")).toBeVisible()
  })

  test('locale-flow-fr', async ({ page, goto }) => {
    await goto("/locale/fr", { waitUntil: 'hydration' })
    await expect(page.locator("[data-mark=\"locale-fr-ok\"]")).toBeVisible()
    await expect(page.locator("[data-mark=\"locale-fr-copy\"]")).toContainText("fr")
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
    await page.locator("[data-nav=\"locale-fr\"]").click()
    await expect(page.locator("[data-mark=\"locale-fr-ok\"]")).toBeVisible()
  })

  test('locale-flow-es', async ({ page, goto }) => {
    await goto("/locale/es", { waitUntil: 'hydration' })
    await expect(page.locator("[data-mark=\"locale-es-ok\"]")).toBeVisible()
    await expect(page.locator("[data-mark=\"locale-es-copy\"]")).toContainText("es")
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
    await page.locator("[data-nav=\"locale-es\"]").click()
    await expect(page.locator("[data-mark=\"locale-es-ok\"]")).toBeVisible()
  })

  test('locale-flow-it', async ({ page, goto }) => {
    await goto("/locale/it", { waitUntil: 'hydration' })
    await expect(page.locator("[data-mark=\"locale-it-ok\"]")).toBeVisible()
    await expect(page.locator("[data-mark=\"locale-it-copy\"]")).toContainText("it")
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
    await page.locator("[data-nav=\"locale-it\"]").click()
    await expect(page.locator("[data-mark=\"locale-it-ok\"]")).toBeVisible()
  })

  test('locale-flow-pt', async ({ page, goto }) => {
    await goto("/locale/pt", { waitUntil: 'hydration' })
    await expect(page.locator("[data-mark=\"locale-pt-ok\"]")).toBeVisible()
    await expect(page.locator("[data-mark=\"locale-pt-copy\"]")).toContainText("pt")
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
    await page.locator("[data-nav=\"locale-pt\"]").click()
    await expect(page.locator("[data-mark=\"locale-pt-ok\"]")).toBeVisible()
  })

  test('locale-flow-nl', async ({ page, goto }) => {
    await goto("/locale/nl", { waitUntil: 'hydration' })
    await expect(page.locator("[data-mark=\"locale-nl-ok\"]")).toBeVisible()
    await expect(page.locator("[data-mark=\"locale-nl-copy\"]")).toContainText("nl")
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
    await page.locator("[data-nav=\"locale-nl\"]").click()
    await expect(page.locator("[data-mark=\"locale-nl-ok\"]")).toBeVisible()
  })

  test('locale-flow-pl', async ({ page, goto }) => {
    await goto("/locale/pl", { waitUntil: 'hydration' })
    await expect(page.locator("[data-mark=\"locale-pl-ok\"]")).toBeVisible()
    await expect(page.locator("[data-mark=\"locale-pl-copy\"]")).toContainText("pl")
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
    await page.locator("[data-nav=\"locale-pl\"]").click()
    await expect(page.locator("[data-mark=\"locale-pl-ok\"]")).toBeVisible()
  })

  test('locale-flow-ja', async ({ page, goto }) => {
    await goto("/locale/ja", { waitUntil: 'hydration' })
    await expect(page.locator("[data-mark=\"locale-ja-ok\"]")).toBeVisible()
    await expect(page.locator("[data-mark=\"locale-ja-copy\"]")).toContainText("ja")
    await page.locator('[data-nav="back-home"]').click()
    await expect(page.locator('[data-mark="home-ok"]')).toBeVisible()
    await page.locator("[data-nav=\"locale-ja\"]").click()
    await expect(page.locator("[data-mark=\"locale-ja-ok\"]")).toBeVisible()
  })
})
