import { describe, expect, test } from 'untestutils/vitest';

/**
 * Mass live browser suite file 3/10 — shared Nuxt prepare.
 * Generated by scripts/generate-e2e.mjs — do not hand-edit; re-run generator.
 */
describe('mass-nuxt shared file-03', () => {
  test.override({ harness: 'app' });

  test('item-detail-15', async ({ page, goto }) => {
    await goto('/items/15', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-15-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-15-copy"]')).toContainText('15');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-16-ok"]')).toBeVisible();
  });

  test('item-detail-16', async ({ page, goto }) => {
    await goto('/items/16', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-16-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-16-copy"]')).toContainText('16');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-17-ok"]')).toBeVisible();
  });

  test('item-detail-17', async ({ page, goto }) => {
    await goto('/items/17', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-17-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-17-copy"]')).toContainText('17');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-18-ok"]')).toBeVisible();
  });

  test('item-detail-18', async ({ page, goto }) => {
    await goto('/items/18', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-18-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-18-copy"]')).toContainText('18');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-19-ok"]')).toBeVisible();
  });

  test('item-detail-19', async ({ page, goto }) => {
    await goto('/items/19', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-19-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-19-copy"]')).toContainText('19');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-20-ok"]')).toBeVisible();
  });

  test('item-detail-20', async ({ page, goto }) => {
    await goto('/items/20', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-20-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-20-copy"]')).toContainText('20');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-21-ok"]')).toBeVisible();
  });

  test('item-detail-21', async ({ page, goto }) => {
    await goto('/items/21', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-21-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-21-copy"]')).toContainText('21');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-22-ok"]')).toBeVisible();
  });

  test('item-detail-22', async ({ page, goto }) => {
    await goto('/items/22', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-22-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-22-copy"]')).toContainText('22');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-23-ok"]')).toBeVisible();
  });

  test('item-detail-23', async ({ page, goto }) => {
    await goto('/items/23', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-23-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-23-copy"]')).toContainText('23');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-24-ok"]')).toBeVisible();
  });

  test('item-detail-24', async ({ page, goto }) => {
    await goto('/items/24', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-24-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-24-copy"]')).toContainText('24');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-25-ok"]')).toBeVisible();
  });

  test('item-detail-25', async ({ page, goto }) => {
    await goto('/items/25', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-25-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-25-copy"]')).toContainText('25');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-26-ok"]')).toBeVisible();
  });

  test('item-detail-26', async ({ page, goto }) => {
    await goto('/items/26', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-26-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-26-copy"]')).toContainText('26');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-27-ok"]')).toBeVisible();
  });

  test('item-detail-27', async ({ page, goto }) => {
    await goto('/items/27', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-27-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-27-copy"]')).toContainText('27');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-28-ok"]')).toBeVisible();
  });

  test('item-detail-28', async ({ page, goto }) => {
    await goto('/items/28', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-28-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-28-copy"]')).toContainText('28');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-29-ok"]')).toBeVisible();
  });

  test('item-detail-29', async ({ page, goto }) => {
    await goto('/items/29', { waitUntil: 'hydration' });
    await expect(page.locator('[data-mark="item-29-ok"]')).toBeVisible();
    await expect(page.locator('[data-mark="item-29-copy"]')).toContainText('29');
    await page.locator('[data-nav="next-item"]').click();
    await expect(page.locator('[data-mark="item-30-ok"]')).toBeVisible();
  });
});
